# Configurações do Projeto de ArrobaDigital
project_info:
  name: "BioWeight_PR"
  version: "1.0.0"
  location: "Parana_BR"

camera_setup:
  # Altura recomendada entre 2.5 e 4.0 metros para visão dorsal
  height_meters: 3.0
  angle: "top_down"  # Visão de cima
  distance_to_ground_pixels: 0.0  # Será calculado na calibração

video_specs:
  fps: 30
  resolution:
    width: 1920
    height: 1080
  format: "mp4"

ai_model:
  #'mask_rcnn_coco' ou 'yolov8_segmentation'
  architecture: "mask_rcnn"
  weights_path: "models/weights/cattle_weights_v1.h5"
  confidence_threshold: 0.85  # Só identifica se tiver 85% de certeza
  
processing:
  # Filtro para ignorar se for bezerro ou animal muito pequeno
  min_area_pixels: 50000 
  # Espécie/Raça predominante para ajuste da fórmula de regressão
  breed_focus: "Nelore"